### ISSUE TITLE
Remove binaries from Source code

### ISSUE THREAD

**Issue by CycloneRing** [fuzzybinary/godot_dart#18]
Hi, Please remove compiled binaries from the source code, It made the repo 400MB :)

**Comment by fuzzybinary** [comment]
Hey @CycloneRing -- The alternative is cloning and building [this](https://github.com/fuzzybinary/dart_shared_libray) or downloading the artifacts from the github actions (which only started working recently).

I'll leave them in for now, but I'll look into either having a script to download the correct version from the shared library repo or using git-lfs, which at least would mean you wouldn't need to fetch the history for the binaries.

**Comment by fuzzybinary** [comment]
Binaries have been removed and instructions updated. I haven't modified history so unfortunately the repo size will likely remain big for a bit but it shouldn't get any worse.
